name: Cache Money

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || format('{0}-{1}', github.ref, github.sha) }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: make sys-deps
      - name: Lint
        run: tox run -e lint
      - name: Run tests
        run: tox run -e tests
      - name: Coverage reporting
        run: bash <(curl -s https://codecov.io/bash)
